vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: '%upload_path%'
            upload_destination: '%kernel.project_dir%/public/%upload_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
